//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public int UserId { get; set; }
        public int ContactID { get; set; }
        public string ContactEmail { get; set; }
        public int ContactStrength { get; set; }
        public int DegreeOfSeparation { get; set; }
        public int SharesFood { get; set; }
        public int BoughtFoodFromUser { get; set; }
        public int SoldFoodToUser { get; set; }
    }
}
