//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettingsID { get; set; }
        public int UserID { get; set; }
        public int PrivacySettingsID { get; set; }
        public int ReceiveEmailNotificationID { get; set; }
        public int ReceiveMobileTextNotificationID { get; set; }
        public Nullable<int> Verified { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
    
        public virtual LKUPPrivacySetting LKUPPrivacySetting { get; set; }
        public virtual NotificationFrequency NotificationFrequency { get; set; }
        public virtual NotificationFrequency NotificationFrequency1 { get; set; }
    }
}
